"use client";
import { useState, useEffect } from "react";
import { X, Printer, Bot, FileText, CheckCircle2, ShieldAlert, Activity, Network, Crosshair } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

interface ExportReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  metrics: {
    activeAlerts: number;
    analyzed: number;
    nodes: number;
    latency: number;
  };
}

export function ExportReportModal({ isOpen, onClose, metrics }: ExportReportModalProps) {
  const [isGenerating, setIsGenerating] = useState(true);

  useEffect(() => {
    if (isOpen) {
      setIsGenerating(true);
      const timer = setTimeout(() => {
        setIsGenerating(false);
      }, 2500); // simulate GenAI processing
      return () => clearTimeout(timer);
    }
  }, [isOpen]);

  // Handle ESC key to close
  useEffect(() => {
    const handleEsc = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    window.addEventListener("keydown", handleEsc);
    return () => window.removeEventListener("keydown", handleEsc);
  }, [onClose]);

  if (!isOpen) return null;

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 z-[100] flex items-center justify-center bg-black/40 backdrop-blur-sm p-6 print:p-0 print:bg-white"
        onClick={onClose}
      >
        <motion.div
          initial={{ scale: 0.95, opacity: 0, y: 10 }}
          animate={{ scale: 1, opacity: 1, y: 0 }}
          exit={{ scale: 0.95, opacity: 0, y: 10 }}
          onClick={(e) => e.stopPropagation()}
          className="bg-white rounded-xl shadow-2xl w-full max-w-4xl max-h-[90vh] flex flex-col overflow-hidden relative print:shadow-none print:w-full print:max-w-none print:h-auto print:block"
        >
          {isGenerating ? (
            <div className="flex flex-col items-center justify-center h-[500px]">
              <div className="w-16 h-16 relative mb-6">
                <div className="absolute inset-0 border-4 border-[#E2E8F0] rounded-full" />
                <div className="absolute inset-0 border-4 rounded-full border-t-transparent animate-spin" style={{ borderColor: "#7C3AED", borderTopColor: "transparent" }} />
                <Bot className="absolute inset-0 m-auto w-7 h-7 animate-pulse" style={{ color: "#7C3AED" }} />
              </div>
              <h3 className="text-[#0F172A] font-bold text-xl mb-2">GenAI is compiling the report...</h3>
              <p className="text-[#64748B] text-sm font-mono max-w-md text-center">
                Synthesizing network metrics, active alerts, and anomaly density into a self-explainable dossier.
              </p>
            </div>
          ) : (
            <>
              {/* Header */}
              <div className="flex items-center justify-between p-6 border-b border-[#E2E8F0] bg-[#F8FAFC] print:hidden">
                <div className="flex items-center gap-3">
                  <div className="p-2 rounded" style={{ backgroundColor: "rgba(124, 58, 237, 0.1)", border: "1px solid rgba(124, 58, 237, 0.2)" }}>
                    <FileText className="w-5 h-5" style={{ color: "#7C3AED" }} />
                  </div>
                  <div>
                    <h2 className="text-[#0F172A] font-bold text-lg">STAR AML System Report</h2>
                    <p className="text-[#64748B] text-xs font-mono">Generated by TGNN Copilot</p>
                  </div>
                </div>
                <div className="flex items-center gap-3">
                  <button onClick={() => window.print()} className="flex items-center gap-2 px-4 py-2 bg-white border border-[#E2E8F0] text-[#334155] rounded-lg text-sm font-medium hover:bg-[#F1F5F9] transition-colors shadow-sm">
                    <Printer className="w-4 h-4" />
                    Print / PDF
                  </button>
                  <button onClick={onClose} className="p-2 text-[#64748B] hover:bg-[#E2E8F0] rounded-lg transition-colors">
                    <X className="w-5 h-5" />
                  </button>
                </div>
              </div>

              {/* Report Content - Print Area */}
              <div className="flex-1 overflow-y-auto p-8 print:p-0 bg-white" id="printable-report">
                {/* Print Only Header */}
                <div className="hidden print:flex items-center gap-3 mb-8 border-b border-[#E2E8F0] pb-6">
                  <div className="p-2 rounded" style={{ backgroundColor: "rgba(124, 58, 237, 0.1)", border: "1px solid rgba(124, 58, 237, 0.2)" }}>
                    <FileText className="w-6 h-6" style={{ color: "#7C3AED" }} />
                  </div>
                  <div>
                    <h1 className="text-[#0F172A] font-bold text-2xl tracking-tight">STAR AML System Report</h1>
                    <p className="text-[#64748B] text-sm font-mono mt-1">CONFIDENTIAL DOSSIER • EXPORTED VIA AI COPILOT</p>
                  </div>
                </div>

                <div className="max-w-3xl mx-auto space-y-8 print:max-w-none">
                  {/* Executive Summary */}
                  <section>
                    <div className="flex items-center gap-2 mb-4">
                      <Bot className="w-5 h-5" style={{ color: "#7C3AED" }} />
                      <h3 className="text-[#0F172A] font-bold text-xl">Executive AI Summary</h3>
                    </div>
                    <div className="p-5 rounded-xl bg-[#F8FAFC] border border-[#E2E8F0] shadow-sm print:shadow-none print:border-2">
                      <p className="text-[#334155] leading-relaxed text-sm">
                        Over the last 24 hours, the STAR Spatial Temporal Graph Neural Network (TGNN) pipeline has processed <strong className="text-[#0F172A]">{metrics.analyzed.toLocaleString()}</strong> transactions. 
                        Currently, there are <strong style={{ color: "#DC2626" }}>{metrics.activeAlerts} active alerts</strong> flagged for high-priority review. 
                        The global knowledge graph is actively tracking <strong className="text-[#0F172A]">{metrics.nodes.toLocaleString()}</strong> entity connections with an average scoring latency of <strong style={{ color: "#16A34A" }}>{metrics.latency}ms</strong>, indicating nominal system performance. 
                        Immediate attention is recommended for the alerts classified under structuring and circular trading patterns.
                      </p>
                    </div>
                  </section>

                  {/* Performance Metrics */}
                  <section>
                    <h3 className="text-[#0F172A] font-bold text-lg mb-4 border-b border-[#E2E8F0] pb-2">System Metrics Snapshot</h3>
                    <div className="grid grid-cols-2 gap-4">
                      <div className="p-4 rounded-xl border border-[#E2E8F0] shadow-sm flex items-center justify-between print:shadow-none print:border-2">
                        <div>
                          <p className="text-xs text-[#64748B] font-semibold uppercase tracking-wider mb-1">Active Alerts</p>
                          <p className="text-2xl font-bold" style={{ color: "#DC2626" }}>{metrics.activeAlerts}</p>
                        </div>
                        <div className="w-10 h-10 rounded-full flex items-center justify-center" style={{ backgroundColor: "rgba(220, 38, 38, 0.1)", border: "1px solid rgba(220, 38, 38, 0.2)" }}>
                          <ShieldAlert className="w-5 h-5" style={{ color: "#DC2626" }} />
                        </div>
                      </div>
                      <div className="p-4 rounded-xl border border-[#E2E8F0] shadow-sm flex items-center justify-between print:shadow-none print:border-2">
                        <div>
                          <p className="text-xs text-[#64748B] font-semibold uppercase tracking-wider mb-1">Scoring Latency</p>
                          <p className="text-2xl font-bold" style={{ color: "#16A34A" }}>{metrics.latency}ms</p>
                        </div>
                        <div className="w-10 h-10 rounded-full flex items-center justify-center" style={{ backgroundColor: "rgba(22, 163, 74, 0.1)", border: "1px solid rgba(22, 163, 74, 0.2)" }}>
                          <Crosshair className="w-5 h-5" style={{ color: "#16A34A" }} />
                        </div>
                      </div>
                      <div className="p-4 rounded-xl border border-[#E2E8F0] shadow-sm flex items-center justify-between print:shadow-none print:border-2">
                        <div>
                          <p className="text-xs text-[#64748B] font-semibold uppercase tracking-wider mb-1">Graph Nodes</p>
                          <p className="text-2xl font-bold text-[#0F172A]">{metrics.nodes.toLocaleString()}</p>
                        </div>
                        <div className="w-10 h-10 rounded-full flex items-center justify-center" style={{ backgroundColor: "rgba(124, 58, 237, 0.1)", border: "1px solid rgba(124, 58, 237, 0.2)" }}>
                          <Network className="w-5 h-5" style={{ color: "#7C3AED" }} />
                        </div>
                      </div>
                      <div className="p-4 rounded-xl border border-[#E2E8F0] shadow-sm flex items-center justify-between print:shadow-none print:border-2">
                        <div>
                          <p className="text-xs text-[#64748B] font-semibold uppercase tracking-wider mb-1">Analyzed (24h)</p>
                          <p className="text-2xl font-bold text-[#0F172A]">{metrics.analyzed.toLocaleString()}</p>
                        </div>
                        <div className="w-10 h-10 rounded-full flex items-center justify-center" style={{ backgroundColor: "rgba(26, 86, 219, 0.1)", border: "1px solid rgba(26, 86, 219, 0.2)" }}>
                          <Activity className="w-5 h-5" style={{ color: "#1A56DB" }} />
                        </div>
                      </div>
                    </div>
                  </section>

                  {/* Recommendations */}
                  <section>
                    <h3 className="text-[#0F172A] font-bold text-lg mb-4 border-b border-[#E2E8F0] pb-2">AI Recommendations</h3>
                    <ul className="list-disc pl-5 space-y-2 text-sm text-[#334155]">
                      <li>Initiate manual review of the top 5 critical alerts in the <span className="font-mono text-xs bg-[#F1F5F9] px-1.5 py-0.5 rounded border border-[#E2E8F0]">/alerts</span> queue.</li>
                      <li>Export suspicious subgraphs to SAR drafts for FinCEN reporting.</li>
                      <li>Monitor latency trends during peak transaction hours (12:00 PM - 04:00 PM).</li>
                    </ul>
                  </section>
                  
                  {/* Footer */}
                  <div className="pt-8 mt-8 text-center text-xs text-[#94A3B8] font-mono border-t border-[#E2E8F0]">
                    <p>Report generated securely via STAR Copilot on {new Date().toLocaleString()}</p>
                    <p className="mt-1">CONFIDENTIAL AND PROPRIETARY</p>
                  </div>
                </div>
              </div>
            </>
          )}
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}
